### ISSUE TITLE
is this being maintained?

### ISSUE THREAD

**Issue by vlad4800** [goshippo/shippo-java-sdk#10]
the maven dependency does not exist. is this library being maintained and deployed to maven?

**Comment by AdrianCollinsShippo** [comment]
Thanks for your question @vlad4800. This library is being maintained and we're actively looking at updating maven with our latest SDK.

**Comment by rkeur7** [comment]
We have published our Beta version. Please see info here: https://central.sonatype.com/artifact/com.goshippo/shippo-sdk
If you're using Maven you can import like below
```
<dependency>
    <groupId>com.goshippo</groupId>
    <artifactId>shippo-sdk</artifactId>
    <version>1.0.0-beta</version>
</dependency>
```
